### PR TITLE
Huffman compression fixed thanks to CUE compressor

### LINKED ISSUE #4: Huffman tiles compression doesn't work
[LZ77 test](https://github.com/devkitPro/grit/files/5715483/lz77_test.zip).
[Huffman test](https://github.com/devkitPro/grit/files/5715484/huffman_test.zip).

The two tests above show a sprite which tiles have been compressed with grit: the first one uses LZ77 compression and the second one uses Huffman compression.

While the first one works as expected, the second one shows garbage on the screen.

### PR DESCRIPTION
**Pull request by GValiente**
Huffman compression is replaced with the compressor made by CUE: https://www.romhacking.net/utilities/826/

It fixes #4, and I haven't had any issues with other data I have tested.

Grit is already licensed under GPL V2, but since CUE compressors are licensed under GPL V3 I have added another file with the new license.

### CODE REVIEW

**Comment by mtheall** [comment]
I recently fixed Huffman issues in [tex3ds](https://github.com/devkitPro/tex3ds/commit/4f5de0398851d91b2ee1514dc13ab800f4a808be) and was in talks to port to grit. I will try your test case in #4 to see if it would be fixed.

Unfortunately, you can't simply pull GPLv3 code into a GPLv2 project. Since I'm the author of tex3ds I can license the code to grit as GPLv2 directly.

**Comment by GValiente** [comment]
> Unfortunately, you can't simply pull GPLv3 code into a GPLv2 project.
Damn, that's a shame.
Should I close this pull request or should I wait for your port to grit?

**Comment by GValiente** [comment]
[GPL-Compatible Free Software Licenses](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses):

> Please note that GPLv3 is not compatible with GPLv2 by itself. However, most software released under GPLv2 allows you to use the terms of later versions of the GPL as well. When this is the case, you can use the code under GPLv3 to make the desired combination.

Is this one of those cases?

**Comment by GValiente** [comment]
https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

I think they are not compatible in this case.

**Pull request closed without merging**
